name = "sales-portal"
compatibility_date = "2025-04-01"
pages_build_output_dir = "web/dist"

[vars]
R2_PUBLIC_BASE = ""

[[d1_databases]]
binding = "DB"
database_name = "sales-portal-db"
database_id = "fd065e2a-698f-4a51-ba91-428ba5f22734"

[[r2_buckets]]
binding = "FILES"
bucket_name = "sales-portal-files"
