ALTER TABLE pi ADD COLUMN senderCorp TEXT NOT NULL DEFAULT '';
ALTER TABLE pi ADD COLUMN senderAddress TEXT NOT NULL DEFAULT '';
ALTER TABLE pi ADD COLUMN senderFrom TEXT NOT NULL DEFAULT '';
ALTER TABLE pi ADD COLUMN senderPhone TEXT NOT NULL DEFAULT '';
ALTER TABLE pi ADD COLUMN senderEmail TEXT NOT NULL DEFAULT '';
ALTER TABLE pi ADD COLUMN otherRequirements TEXT NOT NULL DEFAULT '';
